# Generated by Django 3.2.1 on 2021-05-06 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=50)),
                ('edicao', models.CharField(max_length=10)),
                ('numeros_paginas', models.CharField(max_length=10)),
                ('descricao', models.TextField(max_length=4000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'livro',
            },
        ),
    ]
